---
kind: pipeline
type: docker
name: lint

steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint --version
      - hadolint Dockerfile*

trigger:
  event:
    - pull_request
    - push
  ref:
    exclude:
      - refs/heads/renovate/*

---
kind: pipeline
type: docker
name: test

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: mwalbeck/determine-docker-tags
      dry_run: true

trigger:
  event:
    - pull_request

depends_on:
  - lint

---
kind: pipeline
type: docker
name: test_distroless

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.distroless
      repo: mwalbeck/determine-docker-tags
      dry_run: true

trigger:
  event:
    - pull_request

depends_on:
  - lint

---
kind: pipeline
type: docker
name: build and publish

steps:
  - name: determine tags
    image: mwalbeck/determine-docker-tags
    environment:
      VERSION_TYPE: "docker_env"
      APP_NAME: "DETERMINE_DOCKER_TAGS"
      DOCKERFILE_PATH: "Dockerfile"
      APP_ENV: ""
      CUSTOM_TAGS: "latest"
      INCLUDE_MAJOR: "no"

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/determine-docker-tags
  
  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure
trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - lint

---
kind: pipeline
type: docker
name: build and publish distroless

steps:
  - name: determine tags
    image: mwalbeck/determine-docker-tags
    environment:
      VERSION_TYPE: "docker_env"
      APP_NAME: "DETERMINE_DOCKER_TAGS"
      DOCKERFILE_PATH: "Dockerfile.distroless"
      APP_ENV: "distroless"
      CUSTOM_TAGS: "latest-distroless"
      INCLUDE_MAJOR: "no"

  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.distroless
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/determine-docker-tags
  
  - name: notify
    image: plugins/matrix
    settings:
      homeserver: https://matrix.mwalbeck.org
      roomid:
        from_secret: matrix_roomid
      username:
        from_secret: matrix_username
      password:
        from_secret: matrix_password
    when:
      status:
        - success
        - failure
trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - lint
